### ISSUE TITLE
problem executing test with Eclipse|Maven (Windows)

### ISSUE THREAD

**Issue by flavienlaurent** [stephanenicolas/boundbox#9]
Did you know about it?

All *.java files in sandbox folder still remain locked by java process.
First, I thought it was the `JavaFileManager` because `close()` method is never called. So I tried to call `close()` method with no success.

The workaround is really dirty ... I call an unlocker soft:

```
//dirty
String command = "\"C:\\Program Files\\Unlocker\\Unlocker.exe\" " + sandBoxDir.getAbsolutePath() + " -S";
Process exec = Runtime.getRuntime().exec(command);
```

**Comment by stephanenicolas** [comment]
Can you provide more details about the bug ?

I don't see what happens. Who locks who ? Who uses java.nio ?

The workaround is far too dirty to get it's way inside the lib.

S.
Le 26 sept. 2013 13:04, "Flavien Laurent" notifications@github.com a
écrit :

**Comment by flavienlaurent** [comment]
What happens:
When I run boundbox-library tests, the first one succeeds but all others fail cause of

```
java.io.IOException: Unable to delete file: target\sandbox\BoundBoxOfTestClassWithSingleMethod.java
    at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1247)
    at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:903)
    at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:869)
    at org.boundbox.processor.BoundBoxProcessorTest.setup(BoundBoxProcessorTest.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

Using a breakpoint before it fails, I discovered all *.java files in sandbox dir are locked by java process.

Obviously, the workaround is not intented to be added to boundbox library ;)

**Comment by flavienlaurent** [comment]
I've found what is going on.

```
// write meta model to java class file
            try {
                String targetPackageName = classInfo.getTargetPackageName();
                String boundBoxClassName = classInfo.getBoundBoxClassName();

                String boundBoxFQN = targetPackageName.isEmpty() ? boundBoxClassName : targetPackageName + "." + boundBoxClassName;
                JavaFileObject sourceFile = filer.createSourceFile(boundBoxFQN, (Element[]) null);
                Writer out = sourceFile.openWriter();
                boundboxWriter.writeBoundBox(classInfo, out);
            } catch (IOException e) {
                e.printStackTrace();
                error(classElement, e.getMessage());
            }
```

Here, you open a `Writer` on the source file but it's closed in `writeBoundBox` method (btw, in my opinion, it's better to close a `Writer` in same method where it's opened)

So, when `BoundboxWriter` is mocked, it isn't closing the opened `Writer` anymore.
I suggest this modification

```
Writer out = null;
            try {
                String targetPackageName = classInfo.getTargetPackageName();
                String boundBoxClassName = classInfo.getBoundBoxClassName();

                String boundBoxFQN = targetPackageName.isEmpty() ? boundBoxClassName : targetPackageName + "." + boundBoxClassName;
                JavaFileObject sourceFile = filer.createSourceFile(boundBoxFQN, (Element[]) null);
                out = sourceFile.openWriter();
                boundboxWriter.writeBoundBox(classInfo, out);
            } catch (IOException e) {
                e.printStackTrace();
                error(classElement, e.getMessage());
            } finally {
                if(out != null) {
                    try {
                        out.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                        error(classElement, e.getMessage());
                    }
                }
            }
```

and remove close call in BoundBoxWriter

**Comment by stephanenicolas** [comment]
Go ;)
Le 26 sept. 2013 14:57, "Flavien Laurent" notifications@github.com a
écrit :

**Comment by stephanenicolas** [comment]
@flavienlaurent  
I would like us to release version 1.1.0 after you fix that bug. Would you mind to subscribe to the BoundBox discussion group so that we can tchat about releasing today ?

**Comment by flavienlaurent** [comment]
I fix this bug and subscribe to the group this morning

**Comment by stephanenicolas** [comment]
OK. Send a mail on the list when subscribed.
Le 27 sept. 2013 09:06, "Flavien Laurent" notifications@github.com a
écrit :

**Comment by stephanenicolas** [comment]
You should close that issue so :)
